name: Deploy React App

on:
  push:
    branches:
      - release-0  # Change this if your branch is different

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'      
      
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: build      # The folder that contains the build output
