name: Create Release Branch

on:
  workflow_dispatch:  

permissions:
  contents: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Fetch all branches
        run: git fetch --all

      - name: Determine latest release branch
        id: get-latest-release
        run: |
          # Find the latest release-* branch
          latest_branch=$(git branch -r | grep 'release-' | sed 's/origin\///' | sort -V | tail -n 1)
          echo "Latest release branch found: $latest_branch"
          
          # Extract the release number safely
          if [[ -z "$latest_branch" ]]; then
            latest_branch_number=0
          else
            latest_branch_number=$(echo "$latest_branch" | grep -oE '[0-9]+$' || echo "0")
          fi

          # Increment the release number
          new_branch_number=$((latest_branch_number + 1))
          new_branch="release-$new_branch_number"

          echo "NEW_BRANCH=$new_branch" >> $GITHUB_ENV
          echo "New branch to be created: $new_branch"

      - name: Create new release branch from main
        run: |
          git checkout main
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH

      - name: Output new branch name
        run: echo "Successfully created new branch: $NEW_BRANCH"
