name: Create Release Branch

on:
  workflow_dispatch:  

permissions:
  actions: write
  workflows: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Determine latest release branch
        id: get-latest-release
        run: |
          latest_branch=$(git branch -r | grep 'release-' | sed 's/origin\///' | sort -V | tail -n 1)
          echo "Latest release branch found: $latest_branch"

          if [[ -z "$latest_branch" ]]; then
            latest_branch_number=0
          else
            latest_branch_number=$(echo "$latest_branch" | grep -oE '[0-9]+$' || echo "0")
          fi
          
          new_branch_number=$((latest_branch_number + 1))
          new_branch="release-$new_branch_number"

          echo "NEW_BRANCH=$new_branch" >> $GITHUB_ENV
          echo "New branch to be created: $new_branch"

      - name: Create new release branch from main
        run: |
          git checkout main
          git checkout -b $NEW_BRANCH

      - name: Configure Git User
        run: |
          git config --global user.email "sidharth.sharma1@example.com"
          git config --global user.name "Sidharth Sharma"

      - name: Update deploy.yml with new branch name
        run: |
          sed -i "s/release-[0-9]\+/$NEW_BRANCH/g" .github/workflows/deploy.yml
          git add .github/workflows/deploy.yml
          git commit -m "Update deploy.yml for $NEW_BRANCH"

      - name: Push changes
        run: git push origin $NEW_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output new branch name
        run: |
          echo "Successfully created new branch: $NEW_BRANCH"