name: Create Release Branch

on:
  workflow_dispatch:  # Manually trigger the workflow

permissions:
  contents: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Fetch all branches
        run: git fetch --all

      - name: Determine latest release branch
        id: get-latest-release
        run: |
          latest_branch=$(git branch -r | grep 'release-' | sed 's/origin\///' | sort -V | tail -n 1)
          echo "Latest branch: $latest_branch"
          
          if [ -z "$latest_branch" ]; then
            latest_branch_number=0
          else
            latest_branch_number=$(echo $latest_branch | grep -o '[0-9]\+$')
          fi

          new_branch_number=$((latest_branch_number + 1))
          new_branch="release-$new_branch_number"

          echo "NEW_BRANCH=$new_branch" >> $GITHUB_ENV

      - name: Create new release branch
        run: |
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH

      - name: Output new branch name
        run: echo "Created new branch: $NEW_BRANCH"
