name: Create Release Branch and Update Deploy

on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: List all branches
        run: git branch -r

      - name: Get latest release branch
        id: get-branch
        run: |
          latest_branch=$(git branch -r | grep 'release-' | sort -V | tail -n 1)
          echo "Latest branch: $latest_branch"
          if [ -z "$latest_branch" ]; then
            echo "No release branches found. Setting latest_branch_number to 0."
            latest_branch_number=0
          else
            latest_branch_number=$(echo $latest_branch | grep -o '[0-9]\+$')
          fi
          echo "Latest branch number: $latest_branch_number"
          echo "latest_branch_number=$latest_branch_number" >> $GITHUB_ENV

      - name: Create new release branch
        id: create-branch
        run: |
          new_branch_number=$((latest_branch_number + 1))
          new_branch="release-$new_branch_number"
          git checkout -b $new_branch
          echo "new_branch=$new_branch" >> $GITHUB_ENV

      - name: Update deploy.yml in new branch
        run: |
          sed -i "s/release-[0-9]\+/release-$new_branch_number/g" .github/workflows/deploy.yml
          git add .github/workflows/deploy.yml
          git commit -m "Update deploy.yml for release-$new_branch_number"
          git push origin $new_branch

      - name: Create pull request for new branch
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ env.new_branch }}
          title: "Update deploy.yml for release-${{ env.new_branch_number }}"
          body: "This PR updates the deploy.yml file for the new release branch release-${{ env.new_branch_number }}."
          base: main

  update-main-deploy:
    runs-on: ubuntu-latest
    needs: create-release-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update deploy.yml in main branch
        run: |
          sed -i "s/release-[0-9]\+/release-${{ env.new_branch_number }}/g" .github/workflows/deploy.yml
          git add .github/workflows/deploy.yml
          git commit -m "Update deploy.yml for release-${{ env.new_branch_number }}"
          git push origin main

      - name: Create pull request for main branch
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main
          title: "Update deploy.yml for release-${{ env.new_branch_number }}"
          body: "This PR updates the deploy.yml file for the new release branch release-${{ env.new_branch_number }}."
          base: main