name: Create Release Branch and Update Deploy

on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release branch
        id: get-branch
        run: |
          latest_branch=$(git branch -r | grep 'release-' | sort -V | tail -n 1)
          echo "::set-output name=latest_branch::${latest_branch##*/}"

      - name: Create new release branch
        id: create-branch
        run: |
          new_branch="release-$((${{ steps.get-branch.outputs.latest_branch##*- }} + 1))"
          git checkout -b $new_branch
          echo "::set-output name=new_branch::$new_branch"

      - name: Update deploy.yml in new branch
        run: |
          sed -i "s/release-[0-9]\+/release-${{ steps.create-branch.outputs.new_branch##*- }}/g" .github/workflows/deploy.yml
          git add .github/workflows/deploy.yml
          git commit -m "Update deploy.yml for ${{ steps.create-branch.outputs.new_branch }}"
          git push origin ${{ steps.create-branch.outputs.new_branch }}

      - name: Create pull request for new branch
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.create-branch.outputs.new_branch }}
          title: "Update deploy.yml for ${{ steps.create-branch.outputs.new_branch }}"
          body: "This PR updates the deploy.yml file for the new release branch ${{ steps.create-branch.outputs.new_branch }}."
          base: main

  update-main-deploy:
    runs-on: ubuntu-latest
    needs: create-release-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update deploy.yml in main branch
        run: |
          sed -i "s/release-[0-9]\+/release-${{ needs.create-release-branch.outputs.new_branch##*- }}/g" .github/workflows/deploy.yml
          git add .github/workflows/deploy.yml
          git commit -m "Update deploy.yml for ${{ needs.create-release-branch.outputs.new_branch }}"
          git push origin main

      - name: Create pull request for main branch
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main
          title: "Update deploy.yml for ${{ needs.create-release-branch.outputs.new_branch }}"
          body: "This PR updates the deploy.yml file for the new release branch ${{ needs.create-release-branch.outputs.new_branch }}."
          base: main