name: Version Update Automation

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full repo is fetched

      - name: Debug Directory and Files
        run: |
          pwd
          ls -la
          ls -la src  # Check contents of src

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch
        run: |
          BRANCH_NAME="auto-update-v1-to-v4"
          git fetch origin
          if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
            echo "Branch $BRANCH_NAME already exists. Deleting it..."
            git push origin --delete "$BRANCH_NAME"
          fi
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Run version update script
        run: |
          versions=("v1" "v2" "v3" "v4")

          for ((i=0; i<${#versions[@]}-1; i++)); do
              src="src/${versions[i]}"
              dest="src/${versions[i+1]}"

              if [ ! -d "$src" ]; then
                  echo "❌ Error: Source directory $src does not exist!"
                  exit 1
              fi

              mkdir -p "$dest"
              cp -r "$src/"* "$dest/" 2>/dev/null || echo "⚠️ Warning: No files copied from $src"
              
              echo "✅ Copied contents from $src to $dest"

              # Replace version strings inside files
              find "$dest" -type f -exec sed -i "s/This is ${versions[i]}/This is ${versions[i+1]}/g" {} +

              echo "✅ Updated version strings in $dest"
              git diff --stat "$dest"
          done

      - name: Check for changes
        run: |
          git status
          git diff --stat
          if git diff --quiet; then
            echo "No changes detected. Exiting..."
            exit 0
          fi

      - name: Commit and Push Changes
        run: |
          git add -A  # Stage all changes
          git status  # Check what is staged
          git commit -m "Automated update from v1 to v4"
          git push --force origin "$BRANCH_NAME"  # Force push to ensure changes are reflected

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: auto-update-v1-to-v4
          title: "Automated Version Update"
          body: "This PR updates version references from v1 to v4 automatically."
          base: main
